In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv

In [2]:
df = pd.read_csv('/kaggle/input/datasets/rjmanoj/credit-card-customer-churn-prediction/Churn_Modelling.csv')

In [3]:
df.shape

(10000, 14)

In [4]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [6]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [9]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [10]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [11]:
df.drop(columns=['RowNumber' ,'CustomerId' , 'Surname' ] , inplace=True)

In [12]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [15]:
df = pd.get_dummies(df , columns=['Geography' , 'Gender'] , drop_first=True)

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X = df.drop(columns=['Exited'])
y = df['Exited']

In [18]:
X_train , X_test , y_train, y_test = train_test_split(X , y , test_size=0.2 , random_state=1)

In [20]:
X_train.shape , X_test.shape

((8000, 11), (2000, 11))

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scaler = StandardScaler()

In [23]:
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [24]:
X_train_scaled

array([[-0.23082038, -0.94449979, -0.70174202, ...,  1.71490137,
        -0.57273139,  0.91509065],
       [-0.25150912, -0.94449979, -0.35520275, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [-0.3963303 ,  0.77498705,  0.33787579, ...,  1.71490137,
        -0.57273139, -1.09278791],
       ...,
       [ 0.22433188,  0.58393295,  1.3774936 , ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 0.13123255,  0.01077067,  1.03095433, ..., -0.58312392,
        -0.57273139, -1.09278791],
       [ 1.1656695 ,  0.29735181,  0.33787579, ...,  1.71490137,
        -0.57273139,  0.91509065]])

In [25]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [38]:
model = Sequential()

model.add(Dense(11 , activation='relu' , input_dim=11))
model.add(Dense(11 , activation = 'relu'))
model.add(Dense(1 , activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [39]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 11)             │           132 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │            12 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [40]:
model.compile(loss='binary_crossentropy' , optimizer='Adam' , metrics=['accuracy'])

In [41]:
model.fit(X_train_scaled , y_train , epochs = 100 , validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7952 - loss: 0.5357 - val_accuracy: 0.7975 - val_loss: 0.4878
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7987 - loss: 0.4647 - val_accuracy: 0.7975 - val_loss: 0.4533
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8019 - loss: 0.4402 - val_accuracy: 0.7962 - val_loss: 0.4365
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8077 - loss: 0.4264 - val_accuracy: 0.8031 - val_loss: 0.4216
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8169 - loss: 0.4110 - val_accuracy: 0.8150 - val_loss: 0.4042
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8284 - loss: 0.3957 - val_accuracy: 0.8344 - val_loss: 0.3877
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8394 - loss: 0.3826 - val_accuracy: 0.8413 - val_loss: 0.3765
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8456 - loss: 0.3740 - val_accuracy: 0.8519 - val_loss: 0.3683
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8489 - loss: 0.3676 - val_accuracy: 0.8487 - val_loss: 0.3648
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8508 - loss: 0.3627 - val_accuracy: 0.8531 - val_loss: 0.3607
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8527 - loss: 0.3594 - val_accuracy: 0.8481 - val_loss: 0.3587
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8525 - loss: 0.3571 - val_accuracy: 0.8562 - val_loss: 0.3551
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8544 - loss: 0.3546 - val_accuracy: 0.8525 - val_loss: 0.3552
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8558 - loss: 0.3531 - val_accuracy: 0.8556 - val_loss: 0.3544
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8558 - loss: 0.3515 - val_accuracy: 0.8494 - val_loss: 0.3560
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8542 - loss: 0.3506 - val_accuracy: 0.8569 - val_loss: 0.3520
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8567 - loss: 0.3491 - val_accuracy: 0.8556 - val_loss: 0.3512
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8575 - loss: 0.3483 - val_accuracy: 0.8556 - val_loss: 0.3498
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8578 - loss: 0.3469 - val_accuracy: 0.8525 - val_loss: 0.3499
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8583 - loss: 0.3461 - val_accuracy: 0.8525 - val_loss: 0.3508
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3450 - val_accuracy: 0.8550 - val_loss: 0.3481
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8589 - loss: 0.3447 - val_accuracy: 0.8519 - val_loss: 0.3494
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8587 - loss: 0.3438 - val_accuracy: 0.8556 - val_loss: 0.3491
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8586 - loss: 0.3434 - val_accuracy: 0.8550 - val_loss: 0.3478
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8577 - loss: 0.3429 - val_accuracy: 0.8594 - val_loss: 0.3472
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8580 - loss: 0.3422 - val_accuracy: 0.8581 - val_loss: 0.3470
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8578 - loss: 0.3417 - val_accuracy: 0.8531 - val_loss: 0.3484
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8581 - loss: 0.3415 - val_accuracy: 0.8575 - val_loss: 0.3485
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8591 - loss: 0.3408 - val_accuracy: 0.8575 - val_loss: 0.3474
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8606 - loss: 0.3401 - val_accuracy: 0.8575 - val_loss: 0.3451
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8602 - loss: 0.3395 - val_accuracy: 0.8575 - val_loss: 0.3438
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8606 - loss: 0.3392 - val_accuracy: 0.8575 - val_loss: 0.3444
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8594 - loss: 0.3383 - val_accuracy: 0.8587 - val_loss: 0.3426
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8589 - loss: 0.3388 - val_accuracy: 0.8575 - val_loss: 0.3450
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8608 - loss: 0.3378 - val_accuracy: 0.8550 - val_loss: 0.3460
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8592 - loss: 0.3371 - val_accuracy: 0.8575 - val_loss: 0.3442
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8605 - loss: 0.3367 - val_accuracy: 0.8594 - val_loss: 0.3433
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8597 - loss: 0.3361 - val_accuracy: 0.8581 - val_loss: 0.3433
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8622 - loss: 0.3354 - val_accuracy: 0.8587 - val_loss: 0.3440
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8608 - loss: 0.3356 - val_accuracy: 0.8575 - val_loss: 0.3429
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8598 - loss: 0.3353 - val_accuracy: 0.8581 - val_loss: 0.3423
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8597 - loss: 0.3344 - val_accuracy: 0.8600 - val_loss: 0.3444
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8630 - loss: 0.3332 - val_accuracy: 0.8575 - val_loss: 0.3424
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8598 - loss: 0.3335 - val_accuracy: 0.8562 - val_loss: 0.3438
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8620 - loss: 0.3334 - val_accuracy: 0.8594 - val_loss: 0.3420
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8628 - loss: 0.3320 - val_accuracy: 0.8587 - val_loss: 0.3436
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8603 - loss: 0.3329 - val_accuracy: 0.8569 - val_loss: 0.3432
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3326 - val_accuracy: 0.8594 - val_loss: 0.3425
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8603 - loss: 0.3321 - val_accuracy: 0.8606 - val_loss: 0.3412
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8619 - loss: 0.3318 - val_accuracy: 0.8575 - val_loss: 0.3421
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3316 - val_accuracy: 0.8569 - val_loss: 0.3424
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8600 - loss: 0.3316 - val_accuracy: 0.8594 - val_loss: 0.3423
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8611 - loss: 0.3313 - val_accuracy: 0.8569 - val_loss: 0.3425
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8597 - loss: 0.3310 - val_accuracy: 0.8587 - val_loss: 0.3415
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8611 - loss: 0.3307 - val_accuracy: 0.8594 - val_loss: 0.3416
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8605 - loss: 0.3303 - val_accuracy: 0.8619 - val_loss: 0.3419
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8609 - loss: 0.3300 - val_accuracy: 0.8606 - val_loss: 0.3417
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8612 - loss: 0.3298 - val_accuracy: 0.8575 - val_loss: 0.3434
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8609 - loss: 0.3295 - val_accuracy: 0.8550 - val_loss: 0.3410
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3290 - val_accuracy: 0.8594 - val_loss: 0.3402
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8627 - loss: 0.3284 - val_accuracy: 0.8606 - val_loss: 0.3414
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8633 - loss: 0.3285 - val_accuracy: 0.8594 - val_loss: 0.3410
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8628 - loss: 0.3288 - val_accuracy: 0.8606 - val_loss: 0.3414
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3282 - val_accuracy: 0.8587 - val_loss: 0.3405
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8625 - loss: 0.3280 - val_accuracy: 0.8569 - val_loss: 0.3432
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3279 - val_accuracy: 0.8600 - val_loss: 0.3428
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3272 - val_accuracy: 0.8606 - val_loss: 0.3411
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8652 - loss: 0.3268 - val_accuracy: 0.8600 - val_loss: 0.3412
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8639 - loss: 0.3266 - val_accuracy: 0.8569 - val_loss: 0.3441
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8634 - loss: 0.3269 - val_accuracy: 0.8581 - val_loss: 0.3428
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8652 - loss: 0.3258 - val_accuracy: 0.8594 - val_loss: 0.3441
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8636 - loss: 0.3253 - val_accuracy: 0.8587 - val_loss: 0.3408
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3259 - val_accuracy: 0.8606 - val_loss: 0.3436
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8647 - loss: 0.3255 - val_accuracy: 0.8631 - val_loss: 0.3414
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8648 - loss: 0.3252 - val_accuracy: 0.8606 - val_loss: 0.3406
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3251 - val_accuracy: 0.8581 - val_loss: 0.3420
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8630 - loss: 0.3253 - val_accuracy: 0.8594 - val_loss: 0.3408
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8644 - loss: 0.3249 - val_accuracy: 0.8612 - val_loss: 0.3430
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8652 - loss: 0.3247 - val_accuracy: 0.8612 - val_loss: 0.3420
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8647 - loss: 0.3241 - val_accuracy: 0.8587 - val_loss: 0.3417
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8653 - loss: 0.3245 - val_accuracy: 0.8619 - val_loss: 0.3413
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8645 - loss: 0.3244 - val_accuracy: 0.8625 - val_loss: 0.3418
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8639 - loss: 0.3235 - val_accuracy: 0.8569 - val_loss: 0.3451
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8661 - loss: 0.3243 - val_accuracy: 0.8600 - val_loss: 0.3442
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8652 - loss: 0.3234 - val_accuracy: 0.8600 - val_loss: 0.3420
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8647 - loss: 0.3234 - val_accuracy: 0.8594 - val_loss: 0.3435
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3230 - val_accuracy: 0.8581 - val_loss: 0.3433
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8647 - loss: 0.3231 - val_accuracy: 0.8587 - val_loss: 0.3460
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8661 - loss: 0.3229 - val_accuracy: 0.8612 - val_loss: 0.3423
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8648 - loss: 0.3231 - val_accuracy: 0.8606 - val_loss: 0.3433
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8656 - loss: 0.3228 - val_accuracy: 0.8594 - val_loss: 0.3439
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8658 - loss: 0.3228 - val_accuracy: 0.8612 - val_loss: 0.3405
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8661 - loss: 0.3219 - val_accuracy: 0.8619 - val_loss: 0.3435
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8666 - loss: 0.3223 - val_accuracy: 0.8625 - val_loss: 0.3428
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8652 - loss: 0.3224 - val_accuracy: 0.8612 - val_loss: 0.3429
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8644 - loss: 0.3219 - val_accuracy: 0.8594 - val_loss: 0.3437
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8659 - loss: 0.3218 - val_accuracy: 0.8619 - val_loss: 0.3446
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8677 - loss: 0.3206 - val_accuracy: 0.8569 - val_loss: 0.3472
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8645 - loss: 0.3217 - val_accuracy: 0.8625 - val_loss: 0.3430
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8670 - loss: 0.3213 - val_accuracy: 0.8587 - val_loss: 0.3426

In [42]:
model.layers[0].get_weights()

[array([[ 0.2594142 ,  0.13753624, -0.10030154,  0.40928164,  0.42101935,
         -0.00974391, -0.01236702, -0.0287765 ,  0.0301053 ,  0.35468248,
          0.3067047 ],
        [ 0.13826934, -0.6978929 ,  0.3705434 ,  0.39557973, -0.85700756,
         -0.4998905 , -0.51357394, -0.6357718 , -0.4082149 ,  0.65266633,
         -0.39906392],
        [ 0.02108696, -0.14168939, -0.25961667,  0.18546978,  0.4811953 ,
         -0.41333538, -0.06419293,  0.06087521,  0.14490777,  0.17366086,
          0.04201605],
        [-0.08679337,  0.06956838,  0.31125325,  0.09966215, -0.195724  ,
          0.25509578,  0.82210976, -0.511538  ,  0.02926413,  0.39795664,
          0.54906744],
        [-0.8715724 , -0.25127113, -0.2685343 ,  1.2016505 ,  0.05527746,
         -0.36834615,  0.8690136 ,  0.7635347 ,  0.80327207,  0.25909597,
         -0.27231753],
        [-0.6645111 ,  1.2613289 ,  0.09646468, -0.09493905, -0.57087725,
         -0.1839627 ,  0.11128984, -0.39111078,  0.6187079 , -0.21016581,
         -0.4243557 ],
        [-0.7121502 , -0.1276909 , -0.5955676 , -0.4265164 , -0.05385927,
         -0.88436085, -0.07568882, -0.1898164 ,  0.01658013,  0.5939626 ,
         -0.24963075],
        [ 0.1128618 ,  0.03828916, -0.20968798,  0.156697  , -0.08645362,
         -0.22203074,  0.00311036,  0.1081083 ,  0.04865912,  0.04732695,
          0.00434138],
        [ 0.11486827,  0.20614699,  0.19319682, -0.21893121, -0.56553066,
          0.19536728, -0.270767  ,  0.6130801 , -0.75154954, -0.22954239,
         -0.38037512],
        [-0.2117993 , -0.2008828 ,  0.11602505, -0.03504223,  0.36842364,
          0.0215151 ,  0.04222273,  0.05335762,  0.05724466, -0.11432144,
         -0.16937837],
        [ 0.06204243,  0.08570623, -0.36497134, -0.19871317, -0.4688195 ,
         -0.46361026,  0.0724759 ,  0.1469512 ,  0.02503395,  0.17167917,
          0.2853382 ]], dtype=float32),
 array([ 0.50786066,  0.8542115 , -0.06627329, -0.14444178,  0.22930829,
         0.1011024 ,  0.05936181,  0.6368003 ,  0.5547758 ,  0.083808  ,
         1.0600667 ], dtype=float32)]

In [43]:
y_log = model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step

In [44]:
y_pred = np.where(y_log >0.5 , 1 , 0)

In [45]:
from sklearn.metrics import accuracy_score

In [46]:
print(accuracy_score(y_test, y_pred))

0.857